filter:
    excluded_paths: [vendor/*, app/*, web/*]
    
before_commands:
    - "COMPOSER_ROOT_VERSION=1.8.0 composer install"

tools:
    php_cpd: true
    php_pdepend:
        excluded_dirs: [vendor]
    php_loc: true
    php_mess_detector: true
    php_analyzer: true
    php_code_coverage: true
